# Generated by Django 2.0.2 on 2018-04-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLocationInfo',
            fields=[
                ('visited_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'visited_location',
            },
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='address_line3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visitedlocationinfo',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='location.LocationInfo'),
        ),
        migrations.AddField(
            model_name='visitedlocationinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_location_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
