# Generated by Django 2.0.2 on 2018-04-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180424_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitedlocationinfo',
            options={'ordering': ['-updated_time']},
        ),
    ]
