# Generated by Django 2.0.2 on 2018-04-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180424_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('location_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('photo_link', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('review', models.FloatField(blank=True)),
                ('is_active', models.IntegerField(default=1)),
                ('location_det_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_det_info', to='location.LocationInfo')),
            ],
            options={
                'db_table': 'location_details',
            },
        ),
    ]
