# Generated by Django 2.0.2 on 2018-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_locationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='review',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
