# Generated by Django 2.0.2 on 2018-04-24 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('user_friends_id', models.AutoField(primary_key=True, serialize=False)),
                ('are_friends_with', models.BooleanField(default=True)),
                ('is_active', models.IntegerField(default=1)),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_friends',
            },
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'ordering': ['-updated_time']},
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
